on:
  # release:
  #   types: [created]
  push:
    branches: [ master ]

name: Deploy by Ruby on Jets

jobs:
  app-deploy:
    name: AppDeploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: jets deploy
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle install
        bundle exec AWS_REGION=ap-northeast-1 jets deploy


    
